window.PORTFOLIO = {
  links: {
    github: "https://github.com/Taimoor010",
    linkedin: "https://www.linkedin.com/in/taimoorali/",
    marketlens: "marketlens.html",
  },
  projects: [
    {
      slug: "car-price",
      title: "Car Price Prediction App",
      category: "Live ML Tool / Data Product",
      filters: ["Live Tools", "Data Science", "Business Analytics"],
      status: "Live",
      featured: true,
      summary: "A live machine learning tool that estimates used car prices from marketplace listing data.",
      outcome: "Converted raw marketplace listings into a practical price estimation interface.",
      summaryUrl: "project-car-price.html",
      liveUrl: "marketlens.html",
      githubUrl: "https://github.com/Taimoor010/pakwheels-sportage-price-intelligence",
    },
    {
      slug: "electricity-forecasting",
      title: "UK Electricity Price Forecasting & Battery Storage Optimisation",
      category: "Forecasting & Optimisation",
      filters: ["Forecasting & Optimisation", "Data Science", "Business Analytics"],
      status: "Case Study Coming Soon",
      featured: true,
      summary: "Machine learning forecasting and optimisation research for electricity markets and battery energy storage arbitrage.",
      outcome: "R2 0.945 price forecasting performance and +7.3% annual battery arbitrage profit uplift.",
      summaryUrl: "project-electricity.html",
    },
    {
      slug: "marketplace-seller-growth",
      title: "Marketplace Seller Growth Campaigns",
      category: "Marketplace Growth",
      filters: ["Marketplace Growth", "Marketing Analytics", "Business Analytics"],
      status: "Case Study Coming Soon",
      featured: true,
      summary: "Seller acquisition, leaderboard mechanics, incentive design, and campaign participation measurement.",
      outcome: "Built seller registration and engagement mechanics across growth campaigns.",
      summaryUrl: "project-marketplace-growth.html",
    },
    {
      slug: "ads-monetisation",
      title: "Ads Monetisation & Seller Incentive Analysis",
      category: "Marketing Analytics",
      filters: ["Marketing Analytics", "Marketplace Growth", "Business Analytics"],
      status: "Case Study Coming Soon",
      featured: true,
      summary: "Marketplace ads growth strategy, seller monetisation analysis, and incentive performance tracking.",
      outcome: "Focused on take rate, adoption, seller segmentation, and campaign monetisation signals.",
      summaryUrl: "project-ads-monetisation.html",
    },
    {
      slug: "experiment-measurement",
      title: "A/B Testing & Campaign Measurement Framework",
      category: "Experimentation",
      filters: ["Experimentation", "Marketing Analytics", "Business Analytics"],
      status: "Case Study Coming Soon",
      featured: true,
      summary: "Holdout groups, control groups, pre/post analysis, rollout measurement, and incrementality design.",
      outcome: "Designed measurement logic for campaign decisions and launch tracking.",
      summaryUrl: "project-experimentation.html",
    },
  ],
};
